### ISSUE TITLE
[1.16.4] Error when attempting to place in certain Macaw's Furniture containers

### ISSUE THREAD

**Issue by UncleClapton** [Tfarcenim/DropOff#14]
We've been playing with this mod on our server and encountered this error with Macaw's furniture. It seems like the only way to recover from this once it's occurred is to break the afflicted furniture item and restart the server. In singleplayer, reloading the save works as well.

If the world/server is not reloaded, quickstack continues to error for all players within the region that the block existed.

Here's the stacktrace of that error:

```
[14:29:28] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at com.mcwfurnitures.kikoz.storage.FurnitureTileEntityDouble.getCapability(FurnitureTileEntityDouble.java:172) ~[?:1.0]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?]
	at scp002.quickstack.message.C2SPacketRequestDropoff.lambda$getNearbyInventories$5(C2SPacketRequestDropoff.java:159) ~[?:4.0.0]
	at scp002.quickstack.message.C2SPacketRequestDropoff$$Lambda$13225/251708756.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at scp002.quickstack.message.C2SPacketRequestDropoff.getNearbyInventories(C2SPacketRequestDropoff.java:165) ~[?:4.0.0]
	at scp002.quickstack.message.C2SPacketRequestDropoff.handle(C2SPacketRequestDropoff.java:62) ~[?:4.0.0]
	at scp002.quickstack.message.PacketHandler$$Lambda$8393/1418838728.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$11738/945193826.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2454/1482177069.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2456/1993314761.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2094/518804219.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$11726/1583708784.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$11906/722432633.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$11105/485819921.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Attempting to add these blocks to the blacklist actually results in a crash. The crash report can be found here: https://gist.github.com/UncleClapton/96edf88f037d78a5540ccca19ac78d30

**Comment by Tfarcenim** [comment]
No source code? I ain't got time for this shit
![image](https://user-images.githubusercontent.com/44327798/106498817-ca2c4f80-648d-11eb-97be-22d3ee2b64ba.png)

**Comment by Tfarcenim** [comment]
blacklist and move on

**Comment by UncleClapton** [comment]
@Tfarcenim as I said after the stacktrace, blacklisting causes a crash. The gist in the OP is the crash report.

As for the closed source nature of Macaws.. I know it disappoints me as well. I would have loved to PR a fix to this in either this mod or that one, but there's nothing to go off of. 

If there's no way to prevent the crash, tbh I'll just remove Macaws 🤣

**Comment by Tfarcenim** [comment]
Macaw's doesn't care about making it easier to debug their mods, so I won't bother.
